language: julia
os:
    - osx
    - linux
julia:
    - 0.4
    - 0.5
    - nightly
matrix:
  allow_failures:
    - julia: nightly 
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("LibGEOS"); Pkg.test("LibGEOS"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("LibGEOS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
