[general]
library_name = "libgeos"
output_file_path = "../src/libgeos_api.jl"
# prologue_file_path = "prologue.jl"
use_julia_native_enum_type = false
print_using_CEnum = false
use_deterministic_symbol = true
is_local_header_only = true
smart_de_anonymize = true
printer_blacklist = [
]
[codegen]
use_ccall_macro = true
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = false
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = false
