Base.@deprecate prepcontains contains
Base.@deprecate prepcontainsproperly containsproperly
Base.@deprecate prepcoveredby coveredby
Base.@deprecate prepcovers covers
Base.@deprecate prepcrosses crosses
Base.@deprecate prepdisjoint disjoint
Base.@deprecate prepintersects intersects
Base.@deprecate prepoverlaps overlaps
Base.@deprecate preptouches touches
Base.@deprecate prepwithin within
